---
app:
  is-debug: true
  id: share-things
  name: shareThings
  log-level: trace

http:
  ip: 0.0.0.0
  port: 30001
  cors:
    debug: true
    allowed-methods: ["GET", "POST", "PATCH", "PUT", "OPTIONS", "DELETE"]
    allowed-origins:
      - "http://localhost:30001"
    allow-credentials: true
    allowed-headers:
      - "Authorization"
      - "Location"
      - "Charset"
      - "Access-Control-Allow-Origin"
      - "Content-Type"
      - "Origin"
      - "Accept"
      - "Content-Length"
      - "Accept-Encoding"
      - "X-CSRF-Token"
    options-passthrough: true
    exposed-headers:
      - "Location"
      - "Authorization"
      - "Content-Disposition"

postgresql:
  host: 0.0.0.0
  port: "5455"
  username: postgres
  password: pass
  database: shareThings

security:
  salt: "hjqrhjqw1246sdfsdf17ajfhsdfsdfajs"
JWT:
  secret: "fghjkghjkhjkhjklhgjkluyihjbnmwefdsc"
